service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    storage:
      traces: opensearch
  jaeger_storage:
    backends:
      opensearch:
        opensearch:
          server_urls: [http://opensearch:9200]
          indices:
            index_prefix: watermarker
            spans:
              shards: 1
              replicas: 0
            services:
              shards: 1
              replicas: 0
            dependencies:
              shards: 1
              replicas: 0
            sampling:
              shards: 1
              replicas: 0

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  jaeger_storage_exporter:
    trace_storage: opensearch
